from categorizer import offline_categorize

items = [

"AMUL BUTTER 500G",
"NANDINI MILK 1L",
"BRITANNIA LITTLE HEARTS",
"PARLE G BISCUIT",
"TATA TEA GOLD 250G",
"FORTUNE SUNFLOWER OIL 1L",
"DAAWAT BASMATI RICE",
"AASHIRVAAD ATTA 5KG",
"MOONG DAL 1KG",
"SUGAR 1KG",
"POTATO 2KG",
"ONION 1KG",
"TOMATO 500G",
"LAYS CLASSIC SALTED",
"KURKURE MASALA MUNCH",
"MAGGI MASALA NOODLES",

"SURF EXCEL POWDER",
"ARIEL MATIC FRONTLOAD",
"VIM LIQUID DISHWASH",
"HARPIC POWER PLUS",
"DETTOL FLOOR CLEANER",

"COLGATE MAXFRESH",
"CLOSEUP RED HOT",
"DOVE SOAP 3PACK",
"HEAD AND SHOULDERS",
"NIVEA BODY LOTION",

"CELLO BALL PEN",
"CLASSMATE NOTEBOOK",
"DOMS PENCIL",
"APSARA ERASER"

]

offline_categorize(items)